name = "Catalyst"
uuid = "01e5440a-74e3-4b45-b8b9-c13ddfc5051b"
authors = ["Maximilian KÃ¶hler <maximilian.koehler@ruhr-uni-bochum.de>"]
version = "0.1.0"

[deps]
AlgebraicMultigrid = "2169fc97-5a83-5252-b627-83903c6c433c"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
FFMPEG = "c87230d0-a227-11e9-1b43-d7ebe4e7570a"
Gadfly = "c91e804a-d5a3-530f-b6f0-dfbca275c004"
Hwloc = "0e44f5e4-bd66-52a0-8798-143a42290a1d"
IterativeSolvers = "42fd0dbc-a981-5370-80f2-aaf504508153"
JuAFEM = "30d91d44-8115-11e8-1d28-c19a5ac16de8"
OpenBLAS_jll = "4536629a-c528-5b80-bd46-f80d51c5b363"
PGFPlotsX = "8314cec4-20b6-5062-9cdb-752b83310925"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Preconditioners = "af69fa37-3177-5a40-98ee-561f696e4fcd"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SharedArrays = "1a1011a3-84de-559e-8e89-a11a2f7dc383"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Tensors = "48a634ad-e948-5137-8d70-aa71f2a747f4"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"

[compat]
julia = "1.4.1"
